### ISSUE TITLE
Not working in txt files

### ISSUE THREAD

**Issue by werunom** [IMFUZZ/vscode_banner_comments#4]
Hello! Thanks for this lovely extension. Has been very helpful while writing long (academic) notes and papers (to separate different chapters and sections).

Lately, the extension is not working in txt files. I get this pop-up error: "Command 'Banner comments: Apply h1 font' resulted in an error (Unexpected token })".  However, the extension works fine in other places, say in latex files (*.tex files). 

System configuration
VS Code - Version: 1.63.2
Extension - the latest version available in the marketplace
OS - Mac Monterey

Note: I have observed the same error being thrown in earlier versions of code in my linux desktop. 

Below is the log:

```
[2021-12-22 14:37:25.780] [exthost] [info] ExtensionService#_doActivateExtension heyimfuzz.banner-comments, startup: false, activationEvent: 'onCommand:extension.bannerCommentApplyH1'
[2021-12-22 14:37:25.803] [exthost] [error] SyntaxError: Unexpected token }
	at unexpected (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/json-parser/index.js:121:9)
	at expect (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/json-parser/index.js:115:5)
	at parse_object (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/json-parser/index.js:140:5)
	at walk (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/json-parser/index.js:91:14)
	at Object.parse (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/json-parser/index.js:55:16)
	at Object.parse (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/node_modules/comment-json/lib/parse.js:8:17)
	at getLanguageConfig (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/out/extension.js:336:24)
	at getCommentTags (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/out/extension.js:257:22)
	at applyFromHeader (/Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/out/extension.js:100:23)
	at /Users/varun/.vscode/extensions/heyimfuzz.banner-comments-0.3.0/out/extension.js:400:171
	at r._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31080)
	at r.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31622)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13802)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13486)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12148)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10826)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8922
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34341
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
	at n._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:23523)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21057
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15770)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14900
	at Socket.T (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:13813)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) extension.bannerCommentApplyH1 {"value":"heyimfuzz.banner-comments","_lower":"heyimfuzz.banner-comments"}
```

**Comment by daniel-junior-dube** [comment]
Hi!

Sorry for responding so late.

My guess is that there could be a conflict with another extension that provides specific definitions for the file format.

For the extension to apply the correct comment tags, it needs to check through all available extensions in case the file formats supported by vscode aren't sufficient. The "Unexpected token }" error usually happens when parsing JSON and the extension only do parsing on the stuff I mentioned earlier.

I'm going to update the extension pretty soon and I'll see if I can add additional checks that may handle these kind of problems correctly.

If the problem is still present and you have the chance to provide additional information, I keep the issue opened until I can reproduce and fix it. I'll keep you updated.

Thanks!

**Comment by daniel-junior-dube** [comment]
I've pushed a patch (version "0.4.1") which should fix the issue.

**Comment by werunom** [comment]
Just checked. And it works fine. Thanks for fixing this.
